'use client'

import { useMemo, useState } from 'react'
import { countries, frameworkSections } from '../data/countries'
import { countryFacts } from '../data/facts'
import { globalFacts } from '../data/globalFacts'
import PillarDetail from '../components/PillarDetail'

const activities = ['First meeting','Relationship building','Pitch / proposal','Negotiation','Closing a deal','New market entry','Deal has stalled']
const industries = ['Technology','Aviation','Government','Professional Services','Food & Beverage','Manufacturing','Tourism','Other']
const checklist = ['I understand the cultural context','I know who the decision-maker is','I have identified key influencers','I have built enough relationship/trust','I understand the hierarchy','I know how direct I should be','I know how disagreement may be expressed','I have considered face and harmony','I understand what “yes” may mean','I understand the decision process','I know the key risks/concerns','I have the right evidence/data','I have clarified the next steps','I am comfortable with the pace']
const flags = {'Afghanistan':'🇦🇫','Armenia':'🇦🇲','Azerbaijan':'🇦🇿','Bahrain':'🇧🇭','Bangladesh':'🇧🇩','Bhutan':'🇧🇹','Brunei':'🇧🇳','Cambodia':'🇰🇭','China':'🇨🇳','Cyprus':'🇨🇾','Georgia':'🇬🇪','India':'🇮🇳','Indonesia':'🇮🇩','Iran':'🇮🇷','Iraq':'🇮🇶','Israel':'🇮🇱','Japan':'🇯🇵','Jordan':'🇯🇴','Kazakhstan':'🇰🇿','Kuwait':'🇰🇼','Kyrgyzstan':'🇰🇬','Laos':'🇱🇦','Lebanon':'🇱🇧','Malaysia':'🇲🇾','Maldives':'🇲🇻','Mongolia':'🇲🇳','Myanmar':'🇲🇲','Nepal':'🇳🇵','North Korea':'🇰🇵','Oman':'🇴🇲','Pakistan':'🇵🇰','Palestine':'🇵🇸','Philippines':'🇵🇭','Qatar':'🇶🇦','Saudi Arabia':'🇸🇦','Singapore':'🇸🇬','South Korea':'🇰🇷','Sri Lanka':'🇱🇰','Syria':'🇸🇾','Taiwan':'🇹🇼','Tajikistan':'🇹🇯','Thailand':'🇹🇭','Timor-Leste':'🇹🇱','Turkey':'🇹🇷','Turkmenistan':'🇹🇲','United Arab Emirates':'🇦🇪','Uzbekistan':'🇺🇿','Vietnam':'🇻🇳','Yemen':'🇾🇪','United States':'🇺🇸','Canada':'🇨🇦','Britain':'🇬🇧','Ireland':'🇮🇪','Australia':'🇦🇺','New Zealand':'🇳🇿','South Africa':'🇿🇦','Germany':'🇩🇪','Austria':'🇦🇹','Switzerland':'🇨🇭','Netherlands':'🇳🇱','Belgium':'🇧🇪','France':'🇫🇷','Italy':'🇮🇹','Spain':'🇪🇸','Portugal':'🇵🇹','Greece':'🇬🇷','Poland':'🇵🇱','Hungary':'🇭🇺','Czech Republic':'🇨🇿','Slovakia':'🇸🇰','Slovenia':'🇸🇮','Croatia':'🇭🇷','Serbia and Montenegro':'🇷🇸','Bulgaria':'🇧🇬','Romania':'🇷🇴','Finland':'🇫🇮','Sweden':'🇸🇪','Norway':'🇳🇴','Denmark':'🇩🇰','Estonia':'🇪🇪','Latvia':'🇱🇻','Lithuania':'🇱🇹','Russia':'🇷🇺','Algeria':'🇩🇿','Egypt':'🇪🇬','Libya':'🇱🇾','Mauritania':'🇲🇷','Morocco':'🇲🇦','Sudan':'🇸🇩','Tunisia':'🇹🇳','West Bank and Gaza':'🇵🇸','Hong Kong':'🇭🇰','Argentina':'🇦🇷','Mexico':'🇲🇽','Brazil':'🇧🇷','Chile':'🇨🇱','Venezuela':'🇻🇪','Colombia':'🇨🇴'}
function frictionScore(country, activity){const base=country.sourceBacked?62:50;const adjustment=activity==='Negotiation'?8:activity==='Closing a deal'?6:activity==='First meeting'?3:0;return Math.min(95,base+adjustment)}

export default function Home(){
 const [countryName,setCountryName]=useState('Indonesia'),[homeMarket,setHomeMarket]=useState('New Zealand'),[activity,setActivity]=useState('Negotiation'),[industry,setIndustry]=useState('Aviation'),[checked,setChecked]=useState([]),[open,setOpen]=useState(null)
 const country=countries.find(c=>c.name===countryName)||countries[0],score=frictionScore(country,activity),facts=countryFacts[country.name]||globalFacts[country.name]||['Explore the country’s history','Ask about local food or traditions','Look for a shared interest'],readiness=Math.round(checked.length/checklist.length*100)
 const toggle=item=>setChecked(v=>v.includes(item)?v.filter(x=>x!==item):[...v,item])
 const brief=useMemo(()=>({open:country.p,power:country.a,communicate:country.c,execute:country.e,watch:score>=65?'Do not assume your home-market sales rhythm will transfer unchanged. Pause and validate the next move.':'Keep your approach flexible and validate the local buying context before making assumptions.'}),[country,score])
 return <main className="app">
  <header className="topbar"><div className="brand"><span className="brand-mark">◎</span><span><b>The Cultural</b><strong>Playbook</strong></span></div><div className="nav-title">PACE Framework</div><nav><span className="active">Dashboard</span><span>Compare</span><span>Resources</span><span>About</span><span className="avatar">C</span></nav></header>
  <div className="layout">
   <aside className="sidebar">
    <div className="side-card"><span className="tag">01 · YOUR SITUATION</span><h3>What are you preparing for?</h3>
     <label>Activity<select value={activity} onChange={e=>setActivity(e.target.value)}>{activities.map(x=><option key={x}>{x}</option>)}</select></label>
     <label>Your home / base market<select value={homeMarket} onChange={e=>setHomeMarket(e.target.value)}><option>New Zealand</option><option>Australia</option><option>United Kingdom</option><option>United States</option><option>Other</option></select></label>
     <label>Where are you engaging?<select value={countryName} onChange={e=>setCountryName(e.target.value)}>{countries.map(c=><option key={c.name}>{c.name}</option>)}</select></label>
     <label>Industry / what are you selling?<select value={industry} onChange={e=>setIndustry(e.target.value)}>{industries.map(x=><option key={x}>{x}</option>)}</select></label>
    </div>
    <div className="side-card readiness"><span className="tag">YOUR PACE READINESS</span><div className="ring"><b>{readiness}%</b><span>Ready</span></div><div className="mini-bars"><span>P Trust <b>{checked.some(x=>x.includes('trust')||x.includes('context'))?'✓':'○'}</b></span><span>A Power <b>{checked.some(x=>x.includes('decision')||x.includes('hierarchy')||x.includes('influencers'))?'✓':'○'}</b></span><span>C Comm <b>{checked.some(x=>x.includes('direct')||x.includes('disagreement')||x.includes('yes'))?'✓':'○'}</b></span><span>E Execute <b>{checked.some(x=>x.includes('risks')||x.includes('evidence')||x.includes('next steps'))?'✓':'○'}</b></span></div><button className="outline" onClick={()=>document.getElementById('checklist').scrollIntoView({behavior:'smooth'})}>View Checklist</button></div>
    <div className="side-card pause-side"><span className="tag">MOMENT OF PAUSE™</span><p>Before you act, check your cultural assumptions.</p><button onClick={()=>setOpen('pause')}>⏸ Take the Pause</button></div>
    <div className="side-card source"><span className="tag">SOURCE BASIS</span><p><b>● Playbook Source Data</b><br/>Uses material currently available in The Cultural Playbook project.</p><p><b>● Framework-Ready</b><br/>PACE structure is ready while deeper source development continues.</p></div>
   </aside>
   <section className="main">
    <section className="country-hero"><div><div className="country-title"><span className="flag">{flags[country.name]||'🌏'}</span><div><h1>{country.name}</h1><p>{activity} <span>•</span> {industry} <span>•</span> From {homeMarket}</p></div></div><span className={country.sourceBacked?'source-good':'source-warn'}>{country.sourceBacked?'● PLAYBOOK SOURCE DATA':'● FRAMEWORK READY'}</span><span className="pill">Global Cultural Intelligence Dashboard</span></div><div className="hero-art">PACE</div></section>
    <section className="panel quick"><div className="section-head"><div><span className="tag">02 · QUICK OVERVIEW</span><h2>Four things to keep front of mind</h2></div><span className="score-pill">Friction {score}/100</span></div><div className="pace-overview">{frameworkSections.map(s=><div className={`overview ${s.key}`} key={s.key}><div className="big-letter">{s.letter}</div><div><b>{s.title}</b><small>{s.stage}</small><p>{country[s.key]}</p></div></div>)}</div></section>
    <div className="three-col"><section className="panel"><div className="panel-title"><span className="tag">03 · ICE-BREAKERS</span><span>Rapport builders</span></div><h2>Three things to talk about</h2><div className="facts">{facts.map((f,i)=><div className="fact" key={f}><span>{i+1}</span><p>{f}</p></div>)}</div><small className="hint">Use these as conversation starters, not assumptions about the person.</small></section>
     <section className="panel"><div className="panel-title"><span className="tag">04 · CULTURAL WATCH-OUTS</span></div><h2>Before you push</h2><div className="watch"><div><b>⚠ Hierarchy & authority</b><p>Identify who really influences the decision, not only who is in the meeting.</p></div><div><b>⚠ Communication</b><p>Listen for context, silence, implication and the possibility of a soft no.</p></div><div><b>⚠ Face & harmony</b><p>Consider whether public disagreement or pressure could damage trust.</p></div></div></section>
     <section className="panel"><div className="panel-title"><span className="tag">05 · AT A GLANCE</span></div><h2>Working profile</h2><div className="glance"><span>Communication <b>Context matters</b></span><span>Decision making <b>Map the network</b></span><span>Relationship <b>Build deliberately</b></span><span>Risk <b>Validate</b></span><span>Pace <b>Adapt</b></span><span>Face / harmony <b>Consider</b></span></div></section></div>
    <section className="panel pace-panel"><div className="section-head"><div><span className="tag">06 · PACE FRAMEWORK</span><h2>Explore the four pillars</h2><p className="pace-explainer">PACE moves from <b>Understand</b> → <b>Apply</b> → <b>Act</b>. First understand the cultural pattern, then translate it to your situation, then decide what you will do differently.</p></div><p>Click a pillar to open its working guidance.</p></div><div className="pace-grid">{frameworkSections.map(s=><button className={`pace-card ${s.key} ${open===s.key?'selected':''}`} key={s.key} onClick={()=>setOpen(open===s.key?null:s.key)}><div className="big-letter">{s.letter}</div><small>{s.stage}</small><h3>{s.title}</h3><p>{country[s.key]}</p><span>{open===s.key?'Close details ↑':'Understand → Apply → Act'}</span></button>)}</div>{open&&open!=='pause'&&<PillarDetail pillar={open} country={country} activity={activity} industry={industry}/>}</section>
    <section className="panel brief"><div className="section-head"><div><span className="tag">07 · YOUR {activity.toUpperCase()} BRIEF</span><h2>Understand → Apply → Act</h2><p>The point of PACE is not to memorise cultural facts. It is to change the decision, behaviour or preparation you make next.</p></div><span className="pill">{industry}</span></div><div className="brief-grid"><div><b>OPEN</b><p>{brief.open}</p></div><div><b>MAP POWER</b><p>{brief.power}</p></div><div><b>COMMUNICATE</b><p>{brief.communicate}</p></div><div><b>EXECUTE</b><p>{brief.execute}</p></div><div><b>INDUSTRY LENS</b><p>For {industry.toLowerCase()}, validate the customer organisation, buying process, regulatory environment and internal stakeholders.</p></div><div><b>BIGGEST WATCH-OUT</b><p>{brief.watch}</p></div></div></section>
    <section className="panel tax"><div><span className="tag">08 · CULTURAL TAX</span><h2>Where could friction cost you?</h2><p>Look for hidden costs before they become commercial problems.</p></div><div className="tax-items"><span>Lost time</span><span>Slower decisions</span><span>Damaged trust</span><span>Misread signals</span><span>Lost margin</span><span>Market-entry risk</span></div></section>
    <section className="panel checklist-panel" id="checklist"><div className="section-head"><div><span className="tag">09 · PRE-MEETING CHECKLIST</span><h2>Are you culturally prepared?</h2><p>Tick each item as you prepare. Your readiness score is based only on your completed checklist.</p></div><div className="check-score"><b>{checked.length}/{checklist.length}</b><span>complete</span></div></div><div className="checks">{checklist.map(item=><label key={item} className={checked.includes(item)?'done':''}><input type="checkbox" checked={checked.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div><button className="reset" onClick={()=>setChecked([])}>Reset checklist</button></section>
    <section className="pause-banner"><div><b>💡 TIP: Use the Moment of Pause™</b><span>before key interactions to challenge your assumptions.</span></div><button onClick={()=>setOpen('pause')}>Take the Pause ⏸</button></section><footer>© The Cultural Playbook · PACE Framework · Global source-informed prototype</footer>
   </section>
  </div>
  {open==='pause'&&<div className="modal-backdrop" onClick={()=>setOpen(null)}><div className="modal" onClick={e=>e.stopPropagation()}><span className="tag">MOMENT OF PAUSE™</span><h2>Pause before you push.</h2><p><b>{flags[country.name]} {country.name}</b> · {activity} · {industry}</p><ol><li>Who actually has authority?</li><li>Have I established enough trust for the next ask?</li><li>How direct should I be?</li><li>Could this create loss of face or damage harmony?</li><li>What might silence, “maybe” or “yes” mean here?</li><li>What is the real next step?</li></ol><button onClick={()=>setOpen(null)}>Continue →</button></div></div>}
 </main>
}
