'use client'
import { useMemo,useState } from 'react'
import { countries } from '../data/countries'
import { buildAdaptation,buildDealStalled,buildScenario,sourceMeta,translateApproach,selfDimensions } from '../data/powerLayer'

const scenarios=['First meeting','Relationship building','Pitch / proposal','Negotiation','Closing a deal','New market entry','Partnership','Deal has stalled','Tender / RFP','Government engagement']
const industries=['Technology','Aviation','Government','Professional Services','Food & Beverage','Manufacturing','Tourism','Other']
const challenges=['No response','Proposal delayed','Decision postponed','Suddenly requesting more detail','Senior stakeholder introduced','Price objection','Verbal agreement but no action']

function Guard(){return <div className="power-guard"><b>PACE PRINCIPLE</b><span>Culture gives you a hypothesis. The individual gives you the answer.</span></div>}
function Source({country}){const m=sourceMeta(country);return <div className="power-source"><b>{m.status}</b><span>WHY THIS MATTERS</span><p>{m.why}</p></div>}
function Card({title,children}){return <section className="power-card"><small>PACE POWER LAYER</small><h2>{title}</h2>{children}</section>}

export function KnowYourself(){const [countryName,setCountryName]=useState('Japan');const [values,setValues]=useState(Object.fromEntries(selfDimensions.map(x=>[x.id,5])));const country=countries.find(x=>x.name===countryName)||countries[0];const result=useMemo(()=>buildAdaptation({self:values,country}),[values,country]);return <main className="power-page"><header><a href="/">PACE</a><b>KNOW YOURSELF</b><nav><a href="/tools">TOOLS</a><a href="/compare">COMPARE</a></nav></header><div className="power-wrap"><Card title="How does your normal style meet this market?"><p className="lead">Rate how you normally work. This is a practical reflection tool, not a personality test.</p><label>Target market<select value={countryName} onChange={e=>setCountryName(e.target.value)}>{countries.map(c=><option key={c.name}>{c.name}</option>)}</select></label><div className="self-grid">{selfDimensions.map(d=><div className="self-row" key={d.id}><b>{d.label}</b><div className="ends"><span>{d.low}</span><span>{d.high}</span></div><input type="range" min="1" max="9" value={values[d.id]} onChange={e=>setValues({...values,[d.id]:Number(e.target.value)})}/></div>)}</div></Card><Card title={`Your adaptation gap · ${country.name}`}><div className="adapt-grid"><div><b>WHERE YOU ALIGN</b>{result.aligned.map(x=><p key={x.id}>✓ {x.label}</p>)}</div><div><b>WHERE YOU MAY NEED TO ADAPT</b>{result.rows.filter(x=>x.gap>=3).slice(0,4).map(x=><p key={x.id}>→ {x.label}</p>)}</div><div><b>BIGGEST RISK</b><p>{result.risk}</p></div><div><b>EASIEST ADAPTATION</b><p>{result.easiest.label}: small changes can create a more comfortable interaction.</p></div><div><b>ONE THING TO REMEMBER</b><p>{result.remember}</p></div></div><Source country={country}/><Guard/></Card></div><style jsx>{styles}</style></main>}

export function TranslateApproach(){const [countryName,setCountryName]=useState('France');const [activity,setActivity]=useState('First meeting');const [text,setText]=useState('I want to get straight into the proposal.');const country=countries.find(x=>x.name===countryName)||countries[0];const result=useMemo(()=>translateApproach({text,country,activity}),[text,country,activity]);return <main className="power-page"><header><a href="/">PACE</a><b>TRANSLATE MY APPROACH</b><nav><a href="/tools">TOOLS</a><a href="/compare">COMPARE</a></nav></header><div className="power-wrap"><Card title="Turn your normal approach into a market-aware play"><div className="translate-controls"><label>Country<select value={countryName} onChange={e=>setCountryName(e.target.value)}>{countries.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Scenario<select value={activity} onChange={e=>setActivity(e.target.value)}>{scenarios.map(x=><option key={x}>{x}</option>)}</select></label></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What would you normally say or do?"/><div className="translate-grid"><div><b>YOUR NORMAL APPROACH</b><p>{result.normal}</p></div><div><b>POSSIBLE CULTURAL FRICTION</b><p>{result.friction}</p></div><div><b>ADAPTED APPROACH</b><p>{result.adapted}</p></div><div><b>WHY</b><p>{result.why}</p></div></div><Guard/><Source country={country}/></Card></div><style jsx>{styles}</style></main>}

export function DealStalled(){const [countryName,setCountryName]=useState('Japan');const [what,setWhat]=useState(challenges[0]);const country=countries.find(x=>x.name===countryName)||countries[0];const result=useMemo(()=>buildDealStalled({what,country}),[what,country]);return <main className="power-page"><header><a href="/">PACE</a><b>DEAL STALLED</b><nav><a href="/tools">TOOLS</a><a href="/compare">COMPARE</a></nav></header><div className="power-wrap"><Card title="Diagnose before you escalate"><label>Country<select value={countryName} onChange={e=>setCountryName(e.target.value)}>{countries.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>What happened?<select value={what} onChange={e=>setWhat(e.target.value)}>{challenges.map(x=><option key={x}>{x}</option>)}</select></label><div className="stall-grid"><div><b>POSSIBLE CULTURAL EXPLANATIONS</b>{result.possible.map(x=><p key={x}>{x}</p>)}</div><div><b>OTHER POSSIBLE EXPLANATIONS</b>{result.other.map(x=><p key={x}>{x}</p>)}</div><div><b>QUESTIONS TO ASK</b>{result.questions.map(x=><p key={x}>? {x}</p>)}</div><div><b>WHAT NOT TO ASSUME</b><p>{result.dont}</p></div><div><b>NEXT ACTION</b><p>{result.next}</p></div></div></Card></div><style jsx>{styles}</style></main>}

export function ScenarioBuilder(){const [countryName,setCountryName]=useState('Japan'),[industry,setIndustry]=useState('Aviation'),[customerType,setCustomerType]=useState('Government agency'),[meetingPurpose,setMeetingPurpose]=useState('First meeting'),[relationshipStage,setRelationshipStage]=useState('New contact'),[dealStage,setDealStage]=useState('Discovery'),[challenge,setChallenge]=useState('');const country=countries.find(x=>x.name===countryName)||countries[0];const brief=useMemo(()=>buildScenario({country,industry,customerType,meetingPurpose,relationshipStage,dealStage,challenge}),[country,industry,customerType,meetingPurpose,relationshipStage,dealStage,challenge]);return <main className="power-page"><header><a href="/">PACE</a><b>SCENARIO BUILDER</b><nav><a href="/tools">TOOLS</a><a href="/compare">COMPARE</a></nav></header><div className="power-wrap"><Card title="Build the situation you actually face"><div className="builder-grid">{[['Country',countryName,setCountryName,countries.map(x=>x.name)],['Industry',industry,setIndustry,industries],['Customer type',customerType,setCustomerType,['Government agency','Enterprise','SME','Regulator','Procurement team','Technical team','Executive sponsor','Channel / local partner']],['Meeting purpose',meetingPurpose,setMeetingPurpose,scenarios],['Relationship stage',relationshipStage,setRelationshipStage,['New contact','Early relationship','Active opportunity','Negotiation','Existing partner']],['Deal stage',dealStage,setDealStage,['Discovery','Proposal','Evaluation','Negotiation','Contracting','Post-decision']]].map(([label,value,setter,opts])=><label key={label}>{label}<select value={value} onChange={e=>setter(e.target.value)}>{opts.map(x=><option key={x}>{x}</option>)}</select></label>)}</div><label>Known challenge<input value={challenge} onChange={e=>setChallenge(e.target.value)} placeholder="What is making this situation difficult?"/></label><div className="scenario-output"><b>PACE SCENARIO BRIEF</b><h2>{brief.scenario}</h2><p>{brief.activityContext}</p><div className="pace-mini"><div><b>P</b>{brief.preparationTrust}</div><div><b>A</b>{brief.alignmentPower}</div><div><b>C</b>{brief.communicationPatterns}</div><div><b>E</b>{brief.executionRisk}</div></div><Source country={country}/></div></Card></div><style jsx>{styles}</style></main>}

const styles=`.power-page{min-height:100vh;background:#f4f6f8;color:#172131;font-family:Inter,system-ui,sans-serif}.power-page header{height:64px;background:#071a2d;color:#fff;display:flex;align-items:center;padding:0 28px;gap:16px}.power-page header a{color:#fff;text-decoration:none;font-size:11px}.power-page header b{font-size:11px;letter-spacing:.08em}.power-page nav{margin-left:auto;display:flex;gap:20px}.power-wrap{max-width:980px;margin:auto;padding:26px 18px}.power-card{background:#fff;border:1px solid #e1e7ed;border-radius:12px;padding:24px;margin-bottom:16px}.power-card>small{font-size:9px;font-weight:800;letter-spacing:.1em;color:#718294}.power-card h2{font-size:23px;margin:5px 0 12px}.lead{font-size:12px;color:#687584}.power-card label{display:block;font-size:10px;font-weight:800;margin:12px 0}.power-card select,.power-card input,.power-card textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;border:1px solid #ccd7e0;border-radius:7px;padding:10px;background:#fff;color:#172131}.power-card textarea{min-height:120px;font:inherit;font-size:12px}.self-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:20px}.self-row{padding:15px;background:#f7f9fb;border-radius:9px}.self-row>b{font-size:11px}.ends{display:flex;justify-content:space-between;font-size:8px;color:#7d8996;margin-top:8px}.self-row input{margin:5px 0 0;padding:0;border:0}.adapt-grid,.translate-grid,.stall-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.adapt-grid>div,.translate-grid>div,.stall-grid>div{background:#f7f9fb;padding:15px;border-radius:8px}.adapt-grid b,.translate-grid b,.stall-grid b{font-size:9px;letter-spacing:.06em}.adapt-grid p,.translate-grid p,.stall-grid p{font-size:10px;line-height:1.5;color:#596878}.power-guard{margin-top:16px;padding:14px;border-left:3px solid #2c7eb5;background:#eef5fa}.power-guard b{display:block;font-size:8px;letter-spacing:.1em}.power-guard span{font-size:11px}.power-source{margin-top:15px;padding-top:12px;border-top:1px solid #e5e9ed}.power-source b{font-size:9px;margin-right:15px}.power-source span{font-size:8px;font-weight:800;color:#6c7a89}.power-source p{font-size:9px;color:#718090}.translate-controls,.builder-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.builder-grid{grid-template-columns:repeat(3,1fr)}.scenario-output{margin-top:18px;padding:18px;background:#eef5fa;border-radius:9px}.scenario-output>b{font-size:9px}.scenario-output h2{font-size:17px}.scenario-output p{font-size:11px}.pace-mini{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pace-mini>div{background:#fff;padding:12px;font-size:10px;line-height:1.4}.pace-mini b{font-size:15px;margin-right:8px}@media(max-width:700px){.self-grid,.adapt-grid,.translate-grid,.stall-grid,.translate-controls,.builder-grid,.pace-mini{grid-template-columns:1fr}.power-page header{padding:0 14px}.power-wrap{padding:14px}.power-card{padding:17px}.power-page nav{gap:10px}}
`
