'use client'

import { useMemo, useState } from 'react'
import { countries } from '../../../data/countries'
import { buildYourPlay } from '../../../data/decisionEngine'
import { getCountryFingerprint, getSourceCoverageReport, runDifferentiationAudit } from '../../../data/differentiationEngine'

const scenarios = ['First Meeting','Relationship Building','Pitch / Proposal','Negotiation','Closing','New Market Entry','Partnership','Deal Stalled','Tender / RFP','Government Engagement']
const pairs = [['Japan','Germany'],['Japan','India'],['Japan','France'],['Japan','United States'],['Japan','New Zealand'],['Germany','India'],['Germany','France'],['Germany','United States'],['France','United States'],['India','United States']]

const styles = { card:{background:'#fff',border:'1px solid #e6e8ec',borderRadius:14,padding:18,marginBottom:18}, grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}, muted:{color:'#66717c',fontSize:13}, select:{width:'100%',marginTop:6,padding:10,border:'1px solid #d9dde2',borderRadius:8} }

export default function SourceAuditPage(){
 const [country,setCountry]=useState('Japan'); const [scenario,setScenario]=useState('First Meeting'); const [compare,setCompare]=useState('Germany')
 const audit=useMemo(()=>runDifferentiationAudit(buildYourPlay),[]); const coverage=useMemo(()=>getSourceCoverageReport(),[]); const fp=useMemo(()=>getCountryFingerprint(country),[country]);
 const left=useMemo(()=>buildYourPlay({country,activity:scenario,industry:'Other'}),[country,scenario]); const right=useMemo(()=>buildYourPlay({country:compare,activity:scenario,industry:'Other'}),[compare,scenario])
 return <main style={{maxWidth:1200,margin:'0 auto',padding:'32px 20px 60px',color:'#17202a'}}>
  <div style={{marginBottom:24}}><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#6b7280'}}>INTERNAL DEVELOPMENT / AUDIT</div><h1 style={{margin:'8px 0',fontSize:32}}>PACE Source & Differentiation Audit</h1><p style={{...styles.muted,maxWidth:850,lineHeight:1.6}}>Country switching is now checked against authoritative 2A1 evidence. Universal guidance can remain shared, but unsupported cultural differences are not invented.</p></div>
  <section style={styles.card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h2 style={{margin:0}}>Quality gate</h2><p style={styles.muted}>Evidence IDs and recommendation keys are compared rather than relying on raw word similarity.</p></div><strong style={{padding:'7px 12px',borderRadius:999,background:audit.status==='PASS'?'#e8f7ee':'#fdecec'}}>{audit.status}</strong></div><div style={{display:'flex',gap:24,marginTop:14,fontSize:13}}><span><b>{audit.scenariosTested}</b> scenarios</span><span><b>{audit.comparisonPairsTested}</b> pairs</span><span><b>{audit.failures.length}</b> flags</span></div></section>
  <section style={styles.card}><h2 style={{marginTop:0}}>Live country-switch test</h2><div style={styles.grid}><label>Country<select value={country} onChange={e=>setCountry(e.target.value)} style={styles.select}>{countries.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value)} style={styles.select}>{scenarios.map(s=><option key={s}>{s}</option>)}</select></label><label>Compare with<select value={compare} onChange={e=>setCompare(e.target.value)} style={styles.select}>{countries.filter(c=>c.name!==country).map(c=><option key={c.name}>{c.name}</option>)}</select></label></div><div style={{...styles.grid,marginTop:16}}>{[['do','DO'],['dont',"DON'T"],['ask','ASK'],['watch','WATCH'],['next','NEXT']].map(([k,l])=><div key={k} style={{border:'1px solid #edf0f2',borderRadius:10,padding:14,fontSize:13,lineHeight:1.55}}><b style={{fontSize:11,color:'#7a828a'}}>{l}</b><div style={{marginTop:7}}><strong>{country}:</strong> {left[k]}</div><div style={{marginTop:8}}><strong>{compare}:</strong> {right[k]}</div></div>)}</div></section>
  <section style={styles.card}><h2 style={{marginTop:0}}>Country fingerprint: {country}</h2><p style={styles.muted}>Only verified 2A1 evidence is eligible. Missing evidence remains a source gap.</p><div style={styles.grid}>{Object.entries(fp.dimensions).map(([d,v])=><div key={d} style={{border:'1px solid #edf0f2',borderRadius:10,padding:12}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{d}</b><small>{v.informationClass}</small></div><p style={{fontSize:12,lineHeight:1.5,color:'#5d6772'}}>{v.sourceEvidence.length?v.sourceEvidence.join(' '):'No verified country-specific evidence in the 2A1 layer.'}</p>{v.evidenceIds.length>0&&<small style={{color:'#8a929a'}}>Evidence: {v.evidenceIds.join(', ')}</small>}</div>)}</div></section>
  <section style={styles.card}><h2 style={{marginTop:0}}>Source coverage report</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Country','Coverage','P','A','C','E','Major gaps','Confidence'].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:'2px solid #e8ebee'}}>{h}</th>)}</tr></thead><tbody>{coverage.map(r=><tr key={r.country}>{[r.country,r.sourceCoverage,r.pacePCoverage,r.paceACoverage,r.paceCCoverage,r.paceECoverage,r.majorEvidenceGaps.join(', ')||'None',r.sourceConfidence].map((x,i)=><td key={i} style={{padding:8,borderBottom:'1px solid #eef0f2',verticalAlign:'top'}}>{x}</td>)}</tr>)}</tbody></table></div></section>
  <section style={styles.card}><h2 style={{marginTop:0}}>Required comparison pairs</h2><div style={styles.grid}>{pairs.map(([a,b])=>{const r=audit.scenarioResults.find(x=>x.leftCountry===a&&x.rightCountry===b&&x.scenario==='First Meeting');return <div key={a+b} style={{padding:10,border:'1px solid #edf0f2',borderRadius:9,fontSize:12}}><b>{a}</b> vs <b>{b}</b><span style={{float:'right'}}>{r?.status||'PASS'}</span></div>})}</div></section>
 </main>
}
